### ISSUE TITLE
How to convert count graphs to E^2 dN/dE graphs 

### ISSUE THREAD

**Issue by siddcodes11** [ranieremenezes/easyFermi#4]
Hey there, while doing the analysis using easyFermi, I am able to generate counts v/s energy graphs but in recent literature they have plotted E^2 dN/dE v/s Energy graphs. Can you please suggest me how can I convert the graph.

**Comment by ranieremenezes** [comment]
Dear @siddcodes11 ,

The SEDs generated by easyFermi are already in E^2 dN/dE v/s Energy. You can give a look here in the YouTube tutorial: https://www.youtube.com/watch?v=OPMOsheCId8&ab_channel=easyFermi

For instance, the SED is shown in the minute 8:30 already in the desired parameters.

Let me know if it helps you.

**Comment by siddcodes11** [comment]
Thank you so much... yes..I got it..
