### ISSUE TITLE
EasyFermi software keeps on running for greater than 2x time with only 5% progress

### ISSUE THREAD

**Issue by Siddhantmanna** [ranieremenezes/easyFermi#5]
Hello , I was doing Fermi-LAT data analysis using easyFermi for coma cluster for 9 years data based on literature.  The run time showed 535 minutes approx but it is more than 36 hours and there is only 5% progress. Can you please help me what am I doing wrong or why is it happening. 

Thanks & Regards

**Comment by ranieremenezes** [comment]
Hi @Siddhantmanna , please send me the file "fermipy.log"

**Comment by Siddhantmanna** [comment]
Hello,

PFA the fermipy.log file

Thanks & Regards.

**Comment by ranieremenezes** [comment]
I can't find the attached file. Could you please send it again?

**Comment by Siddhantmanna** [comment]
PFA the concerned file...is it there now ?

**Comment by ranieremenezes** [comment]
No, it is not attached. Maybe you can simply copy and paste the content of the log file here

**Comment by Siddhantmanna** [comment]
Sure...here it is...can you please see what's causing the problem?
2023-02-07 16:04:17 INFO    GTAnalysis.__init__():
--------------------------------------------------------------------------------
fermipy version v1.2
ScienceTools version 2.2.0
2023-02-07 16:04:17 DEBUG   GTAnalysis.print_config(): Configuration:
binning:
  binsperdec: 8.0
  binsz: 0.1
  coordsys: CEL
  enumbins: null
  hpx_ebin: true
  hpx_order: 10
  hpx_ordering_scheme: RING
  npix: null
  proj: AIT
  projtype: WCS
  roiwidth: 15.0
components: []
curvature:
  Index2: 0.6667
  free_Index2: false
data:
  cacheft1: true
  evfile: /home/siddhant/Desktop/r1/list.txt
  ltcube: null
  scfile:
/home/siddhant/Desktop/r1/spacecraftdata1/L23020223321712170E9867_SC00.fits
extension:
  fit_ebin: false
  fit_position: false
  fix_shape: false
  free_background: false
  free_radius: null
  make_plots: false
  make_tsmap: true
  psf_scale_fn: null
  reoptimize: false
  save_model_map: false
  spatial_model: RadialGaussian
  sqrt_ts_threshold: null
  tsmap_fitter: tsmap
  update: false
  width: []
  width_max: 1.0
  width_min: 0.01
  width_nstep: 21
  write_fits: true
  write_npy: true
fileio:
  logfile: /home/siddhant/Desktop/r1/fermipy.log
  outdir: /home/siddhant/Desktop/r1
  outdir_regex:
  - \.fits$|\.fit$|\.xml$|\.npy$|\.png$|\.pdf$|\.yaml$
  savefits: true
  scratchdir: /scratch
  usescratch: false
  workdir: null
  workdir_regex:
  - \.fits$|\.fit$|\.xml$|\.npy$
gtlike:
  bexpmap: null
  bexpmap_base: null
  bexpmap_roi: null
  bexpmap_roi_base: null
  convolve: true
  edisp: true
  edisp_bins: -2
  edisp_disable:
  - isodiff
  expscale: null
  irfs: P8R3_SOURCE_V3
  llscan_npts: 20
  minbinsz: 0.05
  resample: true
  rfactor: 2
  src_expscale: {}
  srcmap: null
  srcmap_base: null
  use_external_srcmap: false
  use_scaled_srcmap: false
  wmap: null
lightcurve:
  binsz: 86400.0
  free_background: false
  free_params: []
  free_radius: null
  free_sources: []
  make_plots: false
  max_free_sources: 5
  multithread: false
  nbins: null
  nthread: null
  outdir: null
  save_bin_data: true
  shape_ts_threshold: 16.0
  systematic: 0.02
  time_bins: []
  use_local_ltcube: true
  use_scaled_srcmap: false
  write_fits: true
  write_npy: true
localize:
  dtheta_max: 0.5
  fix_shape: false
  free_background: false
  free_radius: null
  make_plots: false
  nstep: 5
  tsmap_fitter: tsmap
  update: true
  write_fits: true
  write_npy: true
logging:
  chatter: 3
  prefix: ''
  verbosity: 2
ltcube:
  binsz: 1.0
  dcostheta: 0.025
  phibins: 0
  use_local_ltcube: false
mc:
  seed: null
model:
  assoc_xmatch_columns:
  - 3FGL_Name
  catalogs:
  - 4FGL
  diffuse: []
  diffuse_dir: []
  diffuse_xml: []
  extdir: null
  extract_diffuse: false
  galdiff:
  - /home/siddhant/Desktop/r1/backgroundmodel1/gll_iem_v07.fits
  isodiff:
  - /home/siddhant/Desktop/r1/backgroundmodel1/iso_P8R3_SOURCE_V3_v1.txt
  limbdiff: []
  merge_sources: true
  sources: []
  src_radius: null
  src_radius_roi: null
  src_roiwidth: 25.0
optimizer:
  init_lambda: 0.0001
  max_iter: 100
  min_fit_quality: 2
  optimizer: MINUIT
  retries: 3
  tol: 0.001
  verbosity: 0
plotting:
  catalogs: []
  cmap: magma
  cmap_resid: RdBu_r
  figsize:
  - 8.0
  - 6.0
  format: png
  graticule_radii: []
  interactive: false
  label_ts_threshold: 0.0
  loge_bounds: []
residmap:
  exclude: []
  loge_bounds: []
  make_plots: false
  model: {}
  use_weights: false
  write_fits: true
  write_npy: true
roiopt:
  max_free_sources: 5
  npred_frac: 0.95
  npred_threshold: 1.0
  shape_ts_threshold: 25.0
  skip: []
sed:
  bin_index: 2.0
  cov_scale: 3.0
  free_background: false
  free_pars: []
  free_radius: null
  make_plots: false
  ul_confidence: 0.95
  use_local_index: false
  write_fits: true
  write_npy: true
selection:
  convtype: null
  dec: 27.98
  emax: 1000000.0
  emin: 100.0
  evclass: 128
  evtype: 3
  filter: null
  glat: null
  glon: null
  logemax: null
  logemin: null
  phasemax: null
  phasemin: null
  ra: 194.95
  radius: null
  roicut: 'no'
  target: null
  tmax: 644198401
  tmin: 239557417
  zmax: 90.0
sourcefind:
  free_params: []
  max_iter: 5
  min_separation: 1.0
  model: {}
  multithread: false
  nthread: null
  sources_per_iter: 4
  sqrt_ts_threshold: 5.0
  tsmap_fitter: tsmap
tscube:
  cov_scale: -1.0
  cov_scale_bb: -1.0
  do_sed: true
  exclude: []
  init_lambda: 0.0
  max_iter: 30
  model: {}
  nnorm: 10
  norm_sigma: 5.0
  remake_test_source: false
  st_scan_level: 0
  tol: 0.001
  tol_type: 0
tsmap:
  exclude: []
  loge_bounds: []
  make_plots: false
  max_kernel_radius: 3.0
  model: {}
  multithread: false
  nthread: null
  write_fits: true
  write_npy: true

2023-02-07 16:04:18 DEBUG   GTAnalysis._create_component(): Creating
Analysis Component: 00
2023-02-07 16:04:18 DEBUG   GTBinnedAnalysis.__init__(): Automatically
setting selection radius to 11.106601717798213 deg
2023-02-07 16:04:18 DEBUG   GTBinnedAnalysis.print_config(): Configuration:
binning:
  binsperdec: 8.0
  binsz: 0.1
  coordsys: CEL
  enumbins: null
  hpx_ebin: true
  hpx_order: 10
  hpx_ordering_scheme: RING
  npix: null
  proj: AIT
  projtype: WCS
  roiwidth: 15.0
data:
  cacheft1: true
  evfile: /home/siddhant/Desktop/r1/list.txt
  ltcube: null
  scfile:
/home/siddhant/Desktop/r1/spacecraftdata1/L23020223321712170E9867_SC00.fits
file_suffix: _00
fileio:
  logfile: /home/siddhant/Desktop/r1/fermipy.log
  outdir: /home/siddhant/Desktop/r1
  outdir_regex:
  - \.fits$|\.fit$|\.xml$|\.npy$|\.png$|\.pdf$|\.yaml$
  savefits: true
  scratchdir: /scratch
  usescratch: false
  workdir: /home/siddhant/Desktop/r1
  workdir_regex:
  - \.fits$|\.fit$|\.xml$|\.npy$
gtlike:
  bexpmap: null
  bexpmap_base: null
  bexpmap_roi: null
  bexpmap_roi_base: null
  convolve: true
  edisp: true
  edisp_bins: -2
  edisp_disable:
  - isodiff
  expscale: null
  irfs: P8R3_SOURCE_V3
  llscan_npts: 20
  minbinsz: 0.05
  resample: true
  rfactor: 2
  src_expscale: {}
  srcmap: null
  srcmap_base: null
  use_external_srcmap: false
  use_scaled_srcmap: false
  wmap: null
logging:
  chatter: 3
  prefix: ''
  verbosity: 2
ltcube:
  binsz: 1.0
  dcostheta: 0.025
  phibins: 0
  use_local_ltcube: false
model:
  assoc_xmatch_columns:
  - 3FGL_Name
  catalogs:
  - 4FGL
  diffuse: []
  diffuse_dir: []
  diffuse_xml: []
  extdir: null
  extract_diffuse: false
  galdiff:
  - /home/siddhant/Desktop/r1/backgroundmodel1/gll_iem_v07.fits
  isodiff:
  - /home/siddhant/Desktop/r1/backgroundmodel1/iso_P8R3_SOURCE_V3_v1.txt
  limbdiff: []
  merge_sources: true
  sources: []
  src_radius: null
  src_radius_roi: null
  src_roiwidth: 25.0
name: '00'
selection:
  convtype: null
  dec: 27.98
  emax: 1000000.0
  emin: 100.0
  evclass: 128
  evtype: 3
  filter: null
  glat: null
  glon: null
  logemax: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAAGEA=
  logemin: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAAAEA=
  phasemax: null
  phasemin: null
  ra: 194.95
  radius: 11.106601717798213
  roicut: 'no'
  target: null
  tmax: 644198401
  tmin: 239557417
  zmax: 90.0

2023-02-07 16:04:18 INFO    GTAnalysis.setup(): Running setup.
2023-02-07 16:04:18 INFO    GTBinnedAnalysis.setup(): Running setup for
component 00
2023-02-07 16:04:18 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
2023-02-07 16:04:18 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect
infile=/home/siddhant/Desktop/r1/evfile_00.txt
outfile=/home/siddhant/Desktop/r1/ft1_00.fits ra=194.95 dec=27.98
rad=11.106601717798213 tmin=239557417.0 tmax=644198401.0 emin=100.0
emax=1000000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1
phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no
gui=no mode="ql"
2023-02-07 16:04:18 INFO    GTBinnedAnalysis.run_gtapp(): This is gtselect
version HEAD
2023-02-07 16:04:18 INFO    GTBinnedAnalysis.run_gtapp(): Applying filter
string: ((EVENT_CLASS&o200) != o0) && angsep(RA,DEC,194.95,27.98) <
11.10660172 && ((EVENT_TYPE&o3) != o0) && 100 < ENERGY && ENERGY <= 1000000
&& 239557417 < TIME && TIME <= 644198401 && 0 < ZENITH_ANGLE &&
ZENITH_ANGLE <= 90 && gtifilter()
2023-02-07 16:04:30 INFO    GTBinnedAnalysis.run_gtapp(): Done.
2023-02-07 16:04:30 INFO    GTBinnedAnalysis.run_gtapp(): Finished
gtselect. Execution time: 12.46 s
2023-02-07 16:04:30 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2023-02-07 16:04:30 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube
evfile="/home/siddhant/Desktop/r1/ft1_00.fits" evtable="EVENTS"
scfile=/home/siddhant/Desktop/r1/spacecraftdata1/L23020223321712170E9867_SC00.fits
sctable="SC_DATA" outfile=/home/siddhant/Desktop/r1/ltcube_00.fits
dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1"
zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2023-02-07 16:04:30 INFO    GTBinnedAnalysis.run_gtapp(): Working on file
/home/siddhant/Desktop/r1/spacecraftdata1/L23020223321712170E9867_SC00.fits

**Comment by ranieremenezes** [comment]
Hmm, interesting. There is absolutely no problem in the log file. Maybe it is just taking a really long time on your laptop. Here is a test that you can perform:

From the log file, I see that you are using data starting on _tmin: 239557417_ and going up to _tmax: 644198401_ ( which means from 2008-08-04 15:43:36 until 2021-05-31 23:59:56). What I recommend is that you run the same analysis for a much smaller dataset, let's say from 2008-08-04 15:43:36 to 2009-02-04 15:43:36 and check if easyFermi runs the analysis in a reasonable time. If it works, than it means that the 2008-2021 analysis must work as well, but it will take more time than predicted.

On the 5% progress bar: don't worry about it. It is not very precise actually. I will do a much more reliable progress bar in easyFermi V2 (although V2 will take a long time before being released).

Let me know if your analysis runs for this much smaller data sample.

**Comment by Siddhantmanna** [comment]
Thank you so much for your help, I would surely run the program again for
shorter time and let you know. Thank you again

**Comment by Siddhantmanna** [comment]
Hey..yes I did get the SED curves..for one hour time interval. Though I
faced a different problem.
The SED curve I got using easyFermi for
4FGLJ1253.8 + 2929 is attached herein .

But the literature I was following showed the source as 4FGLJ1256.9 + 2736
, and corresponding SED curve is attached.

Why are the graphs different and the sources different when using the same
data..

**Comment by ranieremenezes** [comment]
Hi @Siddhantmanna , the plots are not attached. Please try to attach them by clicking in the bar below the comment box.

**I did get the SED curves..for one hour time interval.** 
- Ah, good! So it works indeed. So I think there was no problem in the first run, it was just very long.

**The SED curve I got using easyFermi for
4FGLJ1253.8 + 2929 is attached herein.
But the literature I was following showed the source as 4FGLJ1256.9 + 2736**
- The names of these two sources are related to their sky coordinates. You got a different result probably because you are not using the same coordinates as in the literature you are following.

Try to attach the plots like this:
![AGN_NASA-1280x720](https://user-images.githubusercontent.com/14879409/217618845-8ccda1ac-5e82-4ed7-b552-ff57068d9dca.jpg)

(you can do it by clicking in the bar below the comment box)

**Comment by Siddhantmanna** [comment]
hey i have attached the sed curves, also i have used the same coordinate as
given in literature: 194.95,27.98 and search radius of 12 degree, can you
please let me know why am i getting different SED curve..

**Comment by ranieremenezes** [comment]
Hello, unfortunately I can't see the SEDs. Is better if you check if the fitted parameters for your source are in agreement with those found in 4FGL-DR3: https://fermi.gsfc.nasa.gov/ssc/data/access/lat/12yr_catalog/

**Comment by Siddhantmanna** [comment]
Thank you..I will surely check it out..and I am extremely sorry , i don't
know why the graphs are not showing.

**Comment by ranieremenezes** [comment]
Since you opened a new issue with the same content as this one (link here: https://github.com/ranieremenezes/easyFermi/issues/6), I will consider this issue here solved.
