### ISSUE TITLE
How to change the model for SED

### ISSUE THREAD

**Issue by suvas0101** [ranieremenezes/easyfermi#7]
Hey, I was analyzing data of quasar 3C279, using easyFermi, it shows that the best fitted model is "PLSuperExpCutoff4" however I wanted to change the model with Powerlaw (PL) & Log-Parabola (LP) models. How I can get SED fitted with LP & PL.

Thanks

**Comment by ranieremenezes** [comment]
Hi @suvas0101 , please take a look at the tutorials. For instance, this one: https://www.youtube.com/watch?v=Ny7aA9EBRUs&t=4s&ab_channel=easyFermi
