### ISSUE TITLE
Which catalog does easyfermi use currently?

### ISSUE THREAD

**Issue by vyaas3305** [ranieremenezes/easyfermi#72]
On the easyfermi interface, if I have selected 4FGL-DR3 catalog, do the data files (photon and spacecraft) being downloaded correspond to their 4FGL-DR3 versions or is the query just returning the newest data files (DR4)? Am I missing something here?

**Comment by ranieremenezes** [comment]
The data is the newest possible version. It is independent of the adopted catalog.
