### ISSUE TITLE
What should I do with this import error?

### ISSUE THREAD

**Issue by mylastexile** [ranieremenezes/easyfermi#9]
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

thank you!

**Comment by ranieremenezes** [comment]
Hello,

Please consider following this guideline: https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo

Otherwise, if the error is in easyFermi or Fermipy, please send me a copy of the fermipy.log file and a print of the easyFermi window

**Comment by mylastexile** [comment]
Thank you! I have work it out by the link address you give. But soon I meet another problem, it's:

 qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

I have solved it by installing VcXsrv(by the way, I use WSL), it took me a long time, so I report it to you in case that someone encounters the same problem.

**Comment by ranieremenezes** [comment]
Hmm, I see. Could you please try to reinstall easyFermi following the tutorial [here](https://github.com/ranieremenezes/easyFermi)? We updated the installation steps yesterday.

Furthermore, are you using a Linux or Mac OS?

**Comment by mylastexile** [comment]
I am sorry I did not express it clearly. I indeed follow the new installation steps and I could run easyfermi already. The problem above is still existence after reinstalling by the new steps, and the way of resolution is mentioned above. I mean that my experience may be helpful.
I am using WSL, it's the Windows subsystem for Linux.

**Comment by ranieremenezes** [comment]
Ok, we updated the installation tutorial of easyFermi. You can check the requirements for WSL. In summary, you need to install libgl1 in your WSL with the following command:

sudo apt-get install libgl1
